#!/bin/sh

feh --bg-scale /home/kyd0/wallpaper/wallpaper2.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar top &

bspc monitor -d I II III IV V

bspc config focus_follows_pointer true
bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#bababa"
bspc config border_width 1
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config gapless_monocle false
bspc config window_gap 10

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a feh state=floating

xsetroot -cursor_name left_ptr

setxkbmap -layout us,ru -option grp:alt_shift_toggle
